name: StatureCheck
main: com.gyozaguy.mclegion.StatureCheck
version: 1.0
depend: [PlayerPoints, WorldGuard]
commands:
 setstature:
  description: Sets a required stature for a WorldGuard region. If a region is not provided, the plugin will attempt to use the region the player is standing in.
  usage: /setstature <stature> [<region>]
  permission: staturecheck.setstature
  permission-message: Oh nosies! You don't have permission to do that!